import streamlit as st
import plotly.graph_objects as go
import requests

# --- CONFIGURATION ---
# IMPORTANT: Change this URL to wherever your FastAPI backend is hosted 
# (e.g., if you deploy the backend to Render, Railway, or keep it on Colab via ngrok/proxy)
API_URL = "http://127.0.0.1:8000/audit"

# --- PAGE CONFIG ---
st.set_page_config(page_title="Green-Truth Auditor", layout="wide", page_icon="🌿")

# --- FUNCTIONS ---
def draw_gauge(score, title="Truth & Transparency Score"):
    """Draws a Plotly gauge chart."""
    fig = go.Figure(go.Indicator(
        mode = "gauge+number",
        value = score,
        domain = {'x': [0, 1], 'y': [0, 1]},
        title = {'text': title, 'font': {'size': 20}},
        gauge = {
            'axis': {'range': [0, 100]},
            'bar': {'color': "#1E1E1E"},
            'steps': [
                {'range': [0, 40], 'color': "#ff4b4b"},    # Red / High Risk
                {'range': [40, 75], 'color': "#ffa500"},   # Orange / Mixed
                {'range': [75, 100], 'color': "#2ecc71"}   # Green / Transparent
            ]}))
    fig.update_layout(height=300, margin=dict(l=20, r=20, t=50, b=20))
    return fig

# --- UI LAYOUT ---
st.title("🌿 Green-Truth Auditor")
st.markdown("Analyze product descriptions for greenwashing using our AI-powered backend.")

# --- INPUT SECTION ---
input_mode = st.radio("Choose Input Method:", ["🔗 URL Analyzer", "📝 Text Description"], horizontal=True)

# Map the UI selection to what the FastAPI backend expects ("url" or "text")
input_type = "url" if "URL" in input_mode else "text"
content = ""

if input_type == "url":
    content = st.text_input("Paste Brand URL:", placeholder="https://www.example.com/product")
else:
    content = st.text_area("Paste Product Description:", height=150, placeholder="Our products are 100% eco-friendly...")

# --- SUBMIT & FETCH ---
if st.button("🚀 Run Deep Audit", type="primary"):
    if len(content.strip()) < 5:
        st.warning("Please enter a valid text or URL.")
    else:
        with st.spinner("Connecting to Backend AI... this may take a few seconds."):
            payload = {
                "input_type": input_type,
                "content": content
            }
            
            try:
                # Send data to the FastAPI backend
                response = requests.post(API_URL, json=payload, timeout=45)
                
                if response.status_code == 200:
                    data = response.json()
                    st.divider()
                    
                    # 1. Top Level Metrics (Backend returns 0.0 to 1.0, gauge expects 0 to 100)
                    score_100 = int(data.get("overall_score", 0) * 100)
                    
                    c1, c2 = st.columns([1, 1.5])
                    with c1:
                        st.plotly_chart(draw_gauge(score_100), width="stretch")
                        
                    with c2:
                        st.subheader(f"Verdict: {data.get('overall_verdict')}")
                        # Display the AI Reasoning Summary generated by the backend
                        st.info(data.get("reasoning_summary", "No summary provided by backend."))
                        st.metric("Total Sentences Analyzed", data.get("total_sentences", 0))

                    st.divider()

                    # 2. Detailed Sentence Breakdown
                    st.subheader("🕵️ Detailed Sentence Breakdown")
                    
                    for s in data.get("sentences", []):
                        verdict = s.get("verdict")
                        text = s.get("sentence")
                        buzzwords = s.get("buzzwords_found", [])
                        evidence = s.get("evidence_keywords", [])
                        
                        if verdict == "EVIDENCE-BASED":
                            with st.expander(f"✅ **PASS:** {text[:80]}..."):
                                st.write(f"**Full Sentence:** {text}")
                                st.success(f"**Evidence Found:** {', '.join(evidence) if evidence else 'Passed via NLP Context'}")
                                
                        elif verdict == "VAGUE":
                            with st.expander(f"❌ **FAIL:** {text[:80]}..."):
                                st.write(f"**Full Sentence:** {text}")
                                st.error(f"**Greenwashing Buzzwords:** {', '.join(buzzwords) if buzzwords else 'Failed via NLP Context'}")
                                
                        else:
                            with st.expander(f"⚠️ **UNCERTAIN:** {text[:80]}..."):
                                st.write(f"**Full Sentence:** {text}")
                                st.warning("Contains mixed signals or lacked strong context.")
                                if buzzwords: st.write(f"- Buzzwords: {', '.join(buzzwords)}")
                                if evidence: st.write(f"- Evidence: {', '.join(evidence)}")

                else:
                    # Handle backend validation errors (e.g., text too short, URL scraping failed)
                    st.error(f"Backend Error: {response.json().get('detail', 'Unknown error')}")
                    
            except requests.exceptions.ConnectionError:
                st.error(f"Could not connect to the backend at `{API_URL}`. Please ensure your FastAPI server is running.")
            except requests.exceptions.Timeout:
                st.error("The backend took too long to respond. The model might still be loading.")
